name: thoi_khoa_bieu
description: "Ứng dụng Thời Khóa Biểu Tuần iOS đồng bộ Cloud API, Offline Cache và Thông báo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_schedule.json
